### ISSUE TITLE
color-scheme

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-vola#13]
IMO vola should be distinguished (e.g. color-wise) from other contents within the admin interface.

**Comment by parsch** [comment]
To apply the vola styles to the dashboard, you need to 
- load the stylesheet via some `Media Class` and
- apply the `css_classes=('vola',)` to the module you create

```
    class Media:
        css = {
            'all': (
                'vola/css/vola.css',
            ),
        }
```

```
    def init_with_context(self, context):
        self.children.append(modules.ModelList(
            _('vola'),
            css_classes=('vola',),
            children=[
                ...
            ]
        ))
```
