### ISSUE TITLE
Legacy Projects

### ISSUE THREAD

**Issue by meksor** [sehmaschine/django-vola#18]
I have the following issue:
I will soon start maintaining a project which uses vola.
Unfortunately the project also uses an insecure version of Django and Python 2

Do you think it makes sense to try and fork/update vola so its compatible with newer Django versions and Python 3 or would it take too much time/require too much refactoring?

I can't say, since I don't know  vola and it's plugin-ecosystem, maybe you can help me out?

**Comment by sehmaschine** [comment]
Hard to say. We actually don't use vola anymore. The Django/Python issues shouldn't be hard to solve IMO. But vola heavily relies on how the Django admin interface works – and that probably changed (quite a bit) in the meantime.

**Comment by meksor** [comment]
Ok I'm just gonna have to take a look then, thank you for your help!
