### ISSUE TITLE
Issues with adding Container instances

### ISSUE THREAD

**Issue by kanu** [sehmaschine/django-vola#6]
VERSIONS:  vola d5be01cb3f83eb9b67466630eecdd98d6b764282, Django 1.6, Grappelli 2.5.0

Adding a Container raises ValidationError [u'ManagementForm data is missing or has been tampered with'], because the add_view expects the inlines (PermissionInline, GroupInline) to be in the POST of the request.

After bypassing this error by using the original change_form template an IntegrityError is raised 'null value in column "preview" violates not-null constraint'.
This could be solved by adding default=False to the Container.preview field definition.

After successfully adding a container the changelist was broken by an IndexError because ContainerAdmin.container_name and .container_languages require the Container to have a group.

**Comment by kanu** [comment]
It seems that there is something wrong with the rearrange inlines feature that removed the inlines from the page.

After removing the 'rearrange inlines'  javascript code from the vola/container/change_form.html the inlines are visible again.

**Comment by sehmaschine** [comment]
containers should work without _any_ errors … but please note that you need grappelli 2.4.8 and django < 1.6!

**Comment by sehmaschine** [comment]
closing this since I updated the requirements info with README. the mentioned issue does not happen with django 1.4/1.5 and grappelli 2.4.8.
